-- MySQL Script generated by MySQL Workbench
-- Sat Apr 28 20:08:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customer_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `EmailAddress` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `idCustomer_UNIQUE` (`customer_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShopMarket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShopMarket` (
  `shopmarket_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`shopmarket_id`),
  UNIQUE INDEX `shopmarket_id_UNIQUE` (`shopmarket_id` ASC),
  UNIQUE INDEX `account_id_UNIQUE` (`customer_id` ASC),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hotel` (
  `hotel_id` INT NOT NULL,
  `hotel_name` VARCHAR(45) NOT NULL,
  `hotel_star` VARCHAR(45) NOT NULL,
  `hotel_hot_index` VARCHAR(45) NOT NULL,
  `hotel_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`hotel_id`),
  UNIQUE INDEX `hotel_id_UNIQUE` (`hotel_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReservationRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReservationRecord` (
  `record_id` INT NOT NULL,
  `shopmarket_id` INT NOT NULL,
  `hotel_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `check_in_date` DATE NOT NULL,
  `check_out_date` DATE NOT NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC),
  INDEX `shopmarket_id_idx` (`shopmarket_id` ASC),
  INDEX `hotel_id_idx` (`hotel_id` ASC),
  CONSTRAINT `shopmarket_id`
    FOREIGN KEY (`shopmarket_id`)
    REFERENCES `mydb`.`ShopMarket` (`shopmarket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hotel_id`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `mydb`.`Hotel` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReservationRecord_has_Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReservationRecord_has_Hotel` (
  `ReservationRecord_record_id` INT NOT NULL,
  `Hotel_hotel_id` INT NOT NULL,
  PRIMARY KEY (`ReservationRecord_record_id`, `Hotel_hotel_id`),
  INDEX `fk_ReservationRecord_has_Hotel_Hotel1_idx` (`Hotel_hotel_id` ASC),
  INDEX `fk_ReservationRecord_has_Hotel_ReservationRecord1_idx` (`ReservationRecord_record_id` ASC),
  CONSTRAINT `fk_ReservationRecord_has_Hotel_ReservationRecord1`
    FOREIGN KEY (`ReservationRecord_record_id`)
    REFERENCES `mydb`.`ReservationRecord` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReservationRecord_has_Hotel_Hotel1`
    FOREIGN KEY (`Hotel_hotel_id`)
    REFERENCES `mydb`.`Hotel` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `room_id` INT NOT NULL,
  `hotel_id` INT NOT NULL,
  `num` VARCHAR(45) NOT NULL,
  `isAvaliable` TINYINT NOT NULL,
  `type` VARCHAR(45) NULL,
  `list_price` VARCHAR(45) NULL,
  PRIMARY KEY (`room_id`),
  UNIQUE INDEX `room_id_UNIQUE` (`room_id` ASC),
  INDEX `hotel_id_idx` (`hotel_id` ASC),
  CONSTRAINT `hotel_id`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `mydb`.`Hotel` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `code` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `hot` VARCHAR(45) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hotel_has_Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hotel_has_Location` (
  `Hotel_hotel_id` INT NOT NULL,
  `Location_code` INT NOT NULL,
  PRIMARY KEY (`Hotel_hotel_id`, `Location_code`),
  INDEX `fk_Hotel_has_Location_Location1_idx` (`Location_code` ASC),
  INDEX `fk_Hotel_has_Location_Hotel1_idx` (`Hotel_hotel_id` ASC),
  CONSTRAINT `fk_Hotel_has_Location_Hotel1`
    FOREIGN KEY (`Hotel_hotel_id`)
    REFERENCES `mydb`.`Hotel` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hotel_has_Location_Location1`
    FOREIGN KEY (`Location_code`)
    REFERENCES `mydb`.`Location` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
